name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up java versions
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: |
          8
          11
          17
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Check Sonar version
      run: curl https://sonarcloud.io/api/server/version
    - name: Check JDK 8 path
      run: |
        export ENV_NAME="JAVA_HOME_8_${{runner.arch}}"
        echo "$ENV_NAME"
        export JAVA_VERSION_PATH=$(printenv $ENV_NAME)
        echo "$JAVA_VERSION_PATH"
        export JAVA_VERSION_PATH = [System.Environment]::GetEnvironmentVariable($ENV_NAME)
        echo $JAVA_VERSION_PATH
    - name: Run Sonar
      run: ./gradlew sonar -Pmodule.sonar.java.jdkHome='echo "JAVA_HOME_8_${env:RUNNER_ARCH}"' "-Dsonar.token=${{secrets.SONAR_TOKEN}}"
