name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up java versions
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: |
          8
          11
          17
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Check Sonar version
      run: curl https://sonarcloud.io/api/server/version
    - name: Run Sonar
      run: |
        export JAVA_8_VERSION="JAVA_HOME_8_${{runner.arch}}"
        echo "Java 8 version: $JAVA_8_VERSION"
        export JAVA_8_PATH=$(printenv $JAVA_8_VERSION)
        echo "Java 8 path: $JAVA_8_PATH"
        ./gradlew sonar -Pmodule.sonar.java.jdkHome='echo "$JAVA_8_PATH"' "-Dsonar.token=${{secrets.SONAR_TOKEN}}"
